
-- Create readings table for sensor data
-- Run this in Supabase SQL editor (or via supabase cli)

create table readings (
  id bigint generated by default as identity primary key,
  device_id text not null,
  pm1 integer not null,
  pm25 integer not null,
  pm10 integer not null,
  aqi integer not null,
  timestamp bigint not null,
  wifi_rssi integer,
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create indexes for better query performance
create index readings_device_id_idx on readings(device_id);
create index readings_timestamp_idx on readings(timestamp);
